function bWinningState = findWinningStates(feasibleStates, nWin)


bWinningState = (all(feasibleStates(:, 1:3) == nWin, 2)) | ...
                (all(feasibleStates(:, 4:6) == nWin, 2)) | ...
                (all(feasibleStates(:, 7:9) == nWin, 2)) | ...
                (all(feasibleStates(:, [1,4,7]) == nWin, 2)) | ...
                (all(feasibleStates(:, [2,5,8]) == nWin, 2)) | ...
                (all(feasibleStates(:, [3,6,9]) == nWin, 2)) | ...
                (all(feasibleStates(:, [1,5,9]) == nWin, 2)) | ...
                (all(feasibleStates(:, [3,5,7]) == nWin, 2));